title: "Vedant Sunil Bhatambrekar"
email: "vb21@illinois.edu"
linkedin: "https://www.linkedin.com/in/vedantbhatambrekar/"
github: "https://github.com/vedantbhatambrekar"
tableau: "https://public.tableau.com/app/profile/vedant.bhatambrekar/vizzes"
description: "Data Analyst | Data Engineer | Software Developer | Cloud Enthusiast"
theme: minima
